### ISSUE TITLE
Error when using yarn

### ISSUE THREAD

**Issue by ncsft** [JosephClay/signal-js#2]
error signal-js@2.1.2: The engine "node" is incompatible with this module. Expected version "10.5.0". Got "11.5.0"
error Found incompatible module

**Comment by JosephClay** [comment]
It appears yarn doesn't like the engine definition in the package.json if the node version doesn't match?

I am not an active user of yarn. Any recommendations?

**Comment by ncsft** [comment]
"engines": {
    "node": ">= 8.0"
  }

**Comment by JosephClay** [comment]
"engines" field has been removed for causing conflicts 04a417056a38cd1928bdff9990990b7bc816b558
