### ISSUE TITLE
Examples doesn't work?

### ISSUE THREAD

**Issue by pleger** [JosephClay/signal-js#3]
Hi everyone, your work is so cool!

I am an extremely newbie in this subject!

var signalJs = require("signal-js")
signalJs.on('basic', arg => console.log(arg));   //BTW, here a ")" is missing your example.
signalJs.emit('basic', 1);

When I execute this, I got: "TypeError: signalJs.on is not a function"

In addition, we try installing this package, I got the following message:
pleger@pleger-mbp cop-js % npm install signal-js
**npm WARN notsup Unsupported engine for signal-js@2.3.2: wanted: {"node":"^10.0.0","npm":"^6.0.0"} (current: {"node":"12.4.0","npm":"6.12.1"})**
npm WARN notsup Not compatible with your version of node/npm: signal-js@2.3.2
npm WARN cop-js@1.0.0 No description
npm WARN cop-js@1.0.0 No repository field.

Finally, when I do: console.log(signalJs.default.VERSION);
it shows "2.0.0" and not "2.3.2", is it ok?

In last addition, when I do:  console.log(signalJs);
{ default: { VERSION: '2.0.0', [Symbol(events)]: Map {} } }

Any answer is welcome! Thanks a lot!

**Comment by JosephClay** [comment]
Thank you @pleger

We're using [`esm`](https://github.com/standard-things/esm) for the node-side. The docs could use some updates, you're seeing a difference between `require` and `import`:

```js
import signal from 'signal-js';
signal.on('basic', arg => console.log(arg));
signal.emit('basic', 1);
```

or 

```js
const { default: signal } = require('signal-js');
signal.on('basic', arg => console.log(arg));
signal.emit('basic', 1);
```

Pull requests to fix are welcome!
